//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.296 版自动生成。
// 
#pragma warning disable 1591

namespace TestConsole.shine.OlCheckCtrlService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="OlCheckCtrlBinding", Namespace="http://ctrl.client.mbap.shine.com/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(olReturnDTO))]
    public partial class OlCheckCtrlService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getLocalCertCheckOperationCompleted;
        
        private System.Threading.SendOrPostCallback submitIdenCheckOperationCompleted;
        
        private System.Threading.SendOrPostCallback reqSMSCodeByPhoneOperationCompleted;
        
        private System.Threading.SendOrPostCallback checkPhoneOperationCompleted;
        
        private System.Threading.SendOrPostCallback checkFullAccountOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryZdQueryRepOperationCompleted;
        
        private System.Threading.SendOrPostCallback addZdQueryReqOperationCompleted;
        
        private System.Threading.SendOrPostCallback addShzdjycxWtOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryShzdjycxHbOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public OlCheckCtrlService() {
            this.Url = global::TestConsole.Properties.Settings.Default.TestConsole_shine_OlCheckCtrlService_OlCheckCtrlService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getLocalCertCheckCompletedEventHandler getLocalCertCheckCompleted;
        
        /// <remarks/>
        public event submitIdenCheckCompletedEventHandler submitIdenCheckCompleted;
        
        /// <remarks/>
        public event reqSMSCodeByPhoneCompletedEventHandler reqSMSCodeByPhoneCompleted;
        
        /// <remarks/>
        public event checkPhoneCompletedEventHandler checkPhoneCompleted;
        
        /// <remarks/>
        public event checkFullAccountCompletedEventHandler checkFullAccountCompleted;
        
        /// <remarks/>
        public event queryZdQueryRepCompletedEventHandler queryZdQueryRepCompleted;
        
        /// <remarks/>
        public event addZdQueryReqCompletedEventHandler addZdQueryReqCompleted;
        
        /// <remarks/>
        public event addShzdjycxWtCompletedEventHandler addShzdjycxWtCompleted;
        
        /// <remarks/>
        public event queryShzdjycxHbCompletedEventHandler queryShzdjycxHbCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getLocalCertCheckResponse", Namespace="http://ctrl.client.mbap.shine.com/")]
        public getLocalCertCheckResponse getLocalCertCheck([System.Xml.Serialization.XmlElementAttribute("getLocalCertCheck", Namespace="http://ctrl.client.mbap.shine.com/")] getLocalCertCheck getLocalCertCheck1) {
            object[] results = this.Invoke("getLocalCertCheck", new object[] {
                        getLocalCertCheck1});
            return ((getLocalCertCheckResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getLocalCertCheckAsync(getLocalCertCheck getLocalCertCheck1) {
            this.getLocalCertCheckAsync(getLocalCertCheck1, null);
        }
        
        /// <remarks/>
        public void getLocalCertCheckAsync(getLocalCertCheck getLocalCertCheck1, object userState) {
            if ((this.getLocalCertCheckOperationCompleted == null)) {
                this.getLocalCertCheckOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetLocalCertCheckOperationCompleted);
            }
            this.InvokeAsync("getLocalCertCheck", new object[] {
                        getLocalCertCheck1}, this.getLocalCertCheckOperationCompleted, userState);
        }
        
        private void OngetLocalCertCheckOperationCompleted(object arg) {
            if ((this.getLocalCertCheckCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getLocalCertCheckCompleted(this, new getLocalCertCheckCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("submitIdenCheckResponse", Namespace="http://ctrl.client.mbap.shine.com/")]
        public submitIdenCheckResponse submitIdenCheck([System.Xml.Serialization.XmlElementAttribute("submitIdenCheck", Namespace="http://ctrl.client.mbap.shine.com/")] submitIdenCheck submitIdenCheck1) {
            object[] results = this.Invoke("submitIdenCheck", new object[] {
                        submitIdenCheck1});
            return ((submitIdenCheckResponse)(results[0]));
        }
        
        /// <remarks/>
        public void submitIdenCheckAsync(submitIdenCheck submitIdenCheck1) {
            this.submitIdenCheckAsync(submitIdenCheck1, null);
        }
        
        /// <remarks/>
        public void submitIdenCheckAsync(submitIdenCheck submitIdenCheck1, object userState) {
            if ((this.submitIdenCheckOperationCompleted == null)) {
                this.submitIdenCheckOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsubmitIdenCheckOperationCompleted);
            }
            this.InvokeAsync("submitIdenCheck", new object[] {
                        submitIdenCheck1}, this.submitIdenCheckOperationCompleted, userState);
        }
        
        private void OnsubmitIdenCheckOperationCompleted(object arg) {
            if ((this.submitIdenCheckCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.submitIdenCheckCompleted(this, new submitIdenCheckCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("reqSMSCodeByPhoneResponse", Namespace="http://ctrl.client.mbap.shine.com/")]
        public reqSMSCodeByPhoneResponse reqSMSCodeByPhone([System.Xml.Serialization.XmlElementAttribute("reqSMSCodeByPhone", Namespace="http://ctrl.client.mbap.shine.com/")] reqSMSCodeByPhone reqSMSCodeByPhone1) {
            object[] results = this.Invoke("reqSMSCodeByPhone", new object[] {
                        reqSMSCodeByPhone1});
            return ((reqSMSCodeByPhoneResponse)(results[0]));
        }
        
        /// <remarks/>
        public void reqSMSCodeByPhoneAsync(reqSMSCodeByPhone reqSMSCodeByPhone1) {
            this.reqSMSCodeByPhoneAsync(reqSMSCodeByPhone1, null);
        }
        
        /// <remarks/>
        public void reqSMSCodeByPhoneAsync(reqSMSCodeByPhone reqSMSCodeByPhone1, object userState) {
            if ((this.reqSMSCodeByPhoneOperationCompleted == null)) {
                this.reqSMSCodeByPhoneOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreqSMSCodeByPhoneOperationCompleted);
            }
            this.InvokeAsync("reqSMSCodeByPhone", new object[] {
                        reqSMSCodeByPhone1}, this.reqSMSCodeByPhoneOperationCompleted, userState);
        }
        
        private void OnreqSMSCodeByPhoneOperationCompleted(object arg) {
            if ((this.reqSMSCodeByPhoneCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.reqSMSCodeByPhoneCompleted(this, new reqSMSCodeByPhoneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("checkPhoneResponse", Namespace="http://ctrl.client.mbap.shine.com/")]
        public checkPhoneResponse checkPhone([System.Xml.Serialization.XmlElementAttribute("checkPhone", Namespace="http://ctrl.client.mbap.shine.com/")] checkPhone checkPhone1) {
            object[] results = this.Invoke("checkPhone", new object[] {
                        checkPhone1});
            return ((checkPhoneResponse)(results[0]));
        }
        
        /// <remarks/>
        public void checkPhoneAsync(checkPhone checkPhone1) {
            this.checkPhoneAsync(checkPhone1, null);
        }
        
        /// <remarks/>
        public void checkPhoneAsync(checkPhone checkPhone1, object userState) {
            if ((this.checkPhoneOperationCompleted == null)) {
                this.checkPhoneOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckPhoneOperationCompleted);
            }
            this.InvokeAsync("checkPhone", new object[] {
                        checkPhone1}, this.checkPhoneOperationCompleted, userState);
        }
        
        private void OncheckPhoneOperationCompleted(object arg) {
            if ((this.checkPhoneCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkPhoneCompleted(this, new checkPhoneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("checkFullAccountResponse", Namespace="http://ctrl.client.mbap.shine.com/")]
        public checkFullAccountResponse checkFullAccount([System.Xml.Serialization.XmlElementAttribute("checkFullAccount", Namespace="http://ctrl.client.mbap.shine.com/")] checkFullAccount checkFullAccount1) {
            object[] results = this.Invoke("checkFullAccount", new object[] {
                        checkFullAccount1});
            return ((checkFullAccountResponse)(results[0]));
        }
        
        /// <remarks/>
        public void checkFullAccountAsync(checkFullAccount checkFullAccount1) {
            this.checkFullAccountAsync(checkFullAccount1, null);
        }
        
        /// <remarks/>
        public void checkFullAccountAsync(checkFullAccount checkFullAccount1, object userState) {
            if ((this.checkFullAccountOperationCompleted == null)) {
                this.checkFullAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckFullAccountOperationCompleted);
            }
            this.InvokeAsync("checkFullAccount", new object[] {
                        checkFullAccount1}, this.checkFullAccountOperationCompleted, userState);
        }
        
        private void OncheckFullAccountOperationCompleted(object arg) {
            if ((this.checkFullAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkFullAccountCompleted(this, new checkFullAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("queryZdQueryRepResponse", Namespace="http://ctrl.client.mbap.shine.com/")]
        public queryZdQueryRepResponse queryZdQueryRep([System.Xml.Serialization.XmlElementAttribute("queryZdQueryRep", Namespace="http://ctrl.client.mbap.shine.com/")] queryZdQueryRep queryZdQueryRep1) {
            object[] results = this.Invoke("queryZdQueryRep", new object[] {
                        queryZdQueryRep1});
            return ((queryZdQueryRepResponse)(results[0]));
        }
        
        /// <remarks/>
        public void queryZdQueryRepAsync(queryZdQueryRep queryZdQueryRep1) {
            this.queryZdQueryRepAsync(queryZdQueryRep1, null);
        }
        
        /// <remarks/>
        public void queryZdQueryRepAsync(queryZdQueryRep queryZdQueryRep1, object userState) {
            if ((this.queryZdQueryRepOperationCompleted == null)) {
                this.queryZdQueryRepOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryZdQueryRepOperationCompleted);
            }
            this.InvokeAsync("queryZdQueryRep", new object[] {
                        queryZdQueryRep1}, this.queryZdQueryRepOperationCompleted, userState);
        }
        
        private void OnqueryZdQueryRepOperationCompleted(object arg) {
            if ((this.queryZdQueryRepCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryZdQueryRepCompleted(this, new queryZdQueryRepCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("addZdQueryReqResponse", Namespace="http://ctrl.client.mbap.shine.com/")]
        public addZdQueryReqResponse addZdQueryReq([System.Xml.Serialization.XmlElementAttribute("addZdQueryReq", Namespace="http://ctrl.client.mbap.shine.com/")] addZdQueryReq addZdQueryReq1) {
            object[] results = this.Invoke("addZdQueryReq", new object[] {
                        addZdQueryReq1});
            return ((addZdQueryReqResponse)(results[0]));
        }
        
        /// <remarks/>
        public void addZdQueryReqAsync(addZdQueryReq addZdQueryReq1) {
            this.addZdQueryReqAsync(addZdQueryReq1, null);
        }
        
        /// <remarks/>
        public void addZdQueryReqAsync(addZdQueryReq addZdQueryReq1, object userState) {
            if ((this.addZdQueryReqOperationCompleted == null)) {
                this.addZdQueryReqOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddZdQueryReqOperationCompleted);
            }
            this.InvokeAsync("addZdQueryReq", new object[] {
                        addZdQueryReq1}, this.addZdQueryReqOperationCompleted, userState);
        }
        
        private void OnaddZdQueryReqOperationCompleted(object arg) {
            if ((this.addZdQueryReqCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addZdQueryReqCompleted(this, new addZdQueryReqCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("addShzdjycxWtResponse", Namespace="http://ctrl.client.mbap.shine.com/")]
        public addShzdjycxWtResponse addShzdjycxWt([System.Xml.Serialization.XmlElementAttribute("addShzdjycxWt", Namespace="http://ctrl.client.mbap.shine.com/")] addShzdjycxWt addShzdjycxWt1) {
            object[] results = this.Invoke("addShzdjycxWt", new object[] {
                        addShzdjycxWt1});
            return ((addShzdjycxWtResponse)(results[0]));
        }
        
        /// <remarks/>
        public void addShzdjycxWtAsync(addShzdjycxWt addShzdjycxWt1) {
            this.addShzdjycxWtAsync(addShzdjycxWt1, null);
        }
        
        /// <remarks/>
        public void addShzdjycxWtAsync(addShzdjycxWt addShzdjycxWt1, object userState) {
            if ((this.addShzdjycxWtOperationCompleted == null)) {
                this.addShzdjycxWtOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddShzdjycxWtOperationCompleted);
            }
            this.InvokeAsync("addShzdjycxWt", new object[] {
                        addShzdjycxWt1}, this.addShzdjycxWtOperationCompleted, userState);
        }
        
        private void OnaddShzdjycxWtOperationCompleted(object arg) {
            if ((this.addShzdjycxWtCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addShzdjycxWtCompleted(this, new addShzdjycxWtCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("queryShzdjycxHbResponse", Namespace="http://ctrl.client.mbap.shine.com/")]
        public queryShzdjycxHbResponse queryShzdjycxHb([System.Xml.Serialization.XmlElementAttribute("queryShzdjycxHb", Namespace="http://ctrl.client.mbap.shine.com/")] queryShzdjycxHb queryShzdjycxHb1) {
            object[] results = this.Invoke("queryShzdjycxHb", new object[] {
                        queryShzdjycxHb1});
            return ((queryShzdjycxHbResponse)(results[0]));
        }
        
        /// <remarks/>
        public void queryShzdjycxHbAsync(queryShzdjycxHb queryShzdjycxHb1) {
            this.queryShzdjycxHbAsync(queryShzdjycxHb1, null);
        }
        
        /// <remarks/>
        public void queryShzdjycxHbAsync(queryShzdjycxHb queryShzdjycxHb1, object userState) {
            if ((this.queryShzdjycxHbOperationCompleted == null)) {
                this.queryShzdjycxHbOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryShzdjycxHbOperationCompleted);
            }
            this.InvokeAsync("queryShzdjycxHb", new object[] {
                        queryShzdjycxHb1}, this.queryShzdjycxHbOperationCompleted, userState);
        }
        
        private void OnqueryShzdjycxHbOperationCompleted(object arg) {
            if ((this.queryShzdjycxHbCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryShzdjycxHbCompleted(this, new queryShzdjycxHbCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ctrl.client.mbap.shine.com/")]
    public partial class getLocalCertCheck {
        
        private string arg0Field;
        
        private string arg1Field;
        
        private string arg2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string arg1 {
            get {
                return this.arg1Field;
            }
            set {
                this.arg1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string arg2 {
            get {
                return this.arg2Field;
            }
            set {
                this.arg2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ctrl.client.mbap.shine.com/")]
    public partial class guDongInfoDTO {
        
        private string certCodeField;
        
        private string certTypeField;
        
        private string custNameField;
        
        private string invAccField;
        
        private string invStatusField;
        
        private string mktCodeField;
        
        private string srcOrderNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string certCode {
            get {
                return this.certCodeField;
            }
            set {
                this.certCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string certType {
            get {
                return this.certTypeField;
            }
            set {
                this.certTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string custName {
            get {
                return this.custNameField;
            }
            set {
                this.custNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string invAcc {
            get {
                return this.invAccField;
            }
            set {
                this.invAccField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string invStatus {
            get {
                return this.invStatusField;
            }
            set {
                this.invStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mktCode {
            get {
                return this.mktCodeField;
            }
            set {
                this.mktCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string srcOrderNo {
            get {
                return this.srcOrderNoField;
            }
            set {
                this.srcOrderNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ctrl.client.mbap.shine.com/")]
    public partial class shzdjycxDTO {
        
        private string clsmField;
        
        private string fhbzField;
        
        private string gjdmField;
        
        private string jshyField;
        
        private string khhyField;
        
        private string khrqField;
        
        private string srcOrderNoField;
        
        private string tzrmcField;
        
        private string xwhField;
        
        private string zjdmField;
        
        private string zjlbField;
        
        private string zqzhField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clsm {
            get {
                return this.clsmField;
            }
            set {
                this.clsmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fhbz {
            get {
                return this.fhbzField;
            }
            set {
                this.fhbzField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gjdm {
            get {
                return this.gjdmField;
            }
            set {
                this.gjdmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string jshy {
            get {
                return this.jshyField;
            }
            set {
                this.jshyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string khhy {
            get {
                return this.khhyField;
            }
            set {
                this.khhyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string khrq {
            get {
                return this.khrqField;
            }
            set {
                this.khrqField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string srcOrderNo {
            get {
                return this.srcOrderNoField;
            }
            set {
                this.srcOrderNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tzrmc {
            get {
                return this.tzrmcField;
            }
            set {
                this.tzrmcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string xwh {
            get {
                return this.xwhField;
            }
            set {
                this.xwhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string zjdm {
            get {
                return this.zjdmField;
            }
            set {
                this.zjdmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string zjlb {
            get {
                return this.zjlbField;
            }
            set {
                this.zjlbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string zqzh {
            get {
                return this.zqzhField;
            }
            set {
                this.zqzhField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(guDongListDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(shzdjyListDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ctrl.client.mbap.shine.com/")]
    public abstract partial class olReturnDTO {
        
        private olReturnMsgDTO msgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public olReturnMsgDTO msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ctrl.client.mbap.shine.com/")]
    public partial class olReturnMsgDTO {
        
        private string errCodeField;
        
        private string errMsgField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string errCode {
            get {
                return this.errCodeField;
            }
            set {
                this.errCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string errMsg {
            get {
                return this.errMsgField;
            }
            set {
                this.errMsgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ctrl.client.mbap.shine.com/")]
    public partial class guDongListDTO : olReturnDTO {
        
        private guDongInfoDTO[] listField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("list", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public guDongInfoDTO[] list {
            get {
                return this.listField;
            }
            set {
                this.listField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ctrl.client.mbap.shine.com/")]
    public partial class shzdjyListDTO : olReturnDTO {
        
        private shzdjycxDTO[] listField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("list", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public shzdjycxDTO[] list {
            get {
                return this.listField;
            }
            set {
                this.listField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ctrl.client.mbap.shine.com/")]
    public partial class getLocalCertCheckResponse {
        
        private olReturnMsgDTO returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public olReturnMsgDTO @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ctrl.client.mbap.shine.com/")]
    public partial class submitIdenCheck {
        
        private string arg0Field;
        
        private string arg1Field;
        
        private string arg2Field;
        
        private string arg3Field;
        
        private string arg4Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string arg1 {
            get {
                return this.arg1Field;
            }
            set {
                this.arg1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string arg2 {
            get {
                return this.arg2Field;
            }
            set {
                this.arg2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string arg3 {
            get {
                return this.arg3Field;
            }
            set {
                this.arg3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string arg4 {
            get {
                return this.arg4Field;
            }
            set {
                this.arg4Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ctrl.client.mbap.shine.com/")]
    public partial class submitIdenCheckResponse {
        
        private olReturnMsgDTO returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public olReturnMsgDTO @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ctrl.client.mbap.shine.com/")]
    public partial class reqSMSCodeByPhone {
        
        private string arg0Field;
        
        private long arg1Field;
        
        private bool arg1FieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg1 {
            get {
                return this.arg1Field;
            }
            set {
                this.arg1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool arg1Specified {
            get {
                return this.arg1FieldSpecified;
            }
            set {
                this.arg1FieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ctrl.client.mbap.shine.com/")]
    public partial class reqSMSCodeByPhoneResponse {
        
        private olReturnMsgDTO returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public olReturnMsgDTO @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ctrl.client.mbap.shine.com/")]
    public partial class checkPhone {
        
        private string arg0Field;
        
        private long arg1Field;
        
        private bool arg1FieldSpecified;
        
        private string arg2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg1 {
            get {
                return this.arg1Field;
            }
            set {
                this.arg1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool arg1Specified {
            get {
                return this.arg1FieldSpecified;
            }
            set {
                this.arg1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string arg2 {
            get {
                return this.arg2Field;
            }
            set {
                this.arg2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ctrl.client.mbap.shine.com/")]
    public partial class checkPhoneResponse {
        
        private olReturnMsgDTO returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public olReturnMsgDTO @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ctrl.client.mbap.shine.com/")]
    public partial class checkFullAccount {
        
        private string arg0Field;
        
        private string arg1Field;
        
        private string arg2Field;
        
        private string arg3Field;
        
        private string arg4Field;
        
        private string arg5Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string arg1 {
            get {
                return this.arg1Field;
            }
            set {
                this.arg1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string arg2 {
            get {
                return this.arg2Field;
            }
            set {
                this.arg2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string arg3 {
            get {
                return this.arg3Field;
            }
            set {
                this.arg3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string arg4 {
            get {
                return this.arg4Field;
            }
            set {
                this.arg4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string arg5 {
            get {
                return this.arg5Field;
            }
            set {
                this.arg5Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ctrl.client.mbap.shine.com/")]
    public partial class checkFullAccountResponse {
        
        private olReturnMsgDTO returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public olReturnMsgDTO @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ctrl.client.mbap.shine.com/")]
    public partial class queryZdQueryRep {
        
        private string arg0Field;
        
        private string arg1Field;
        
        private string arg2Field;
        
        private string arg3Field;
        
        private string arg4Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string arg1 {
            get {
                return this.arg1Field;
            }
            set {
                this.arg1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string arg2 {
            get {
                return this.arg2Field;
            }
            set {
                this.arg2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string arg3 {
            get {
                return this.arg3Field;
            }
            set {
                this.arg3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string arg4 {
            get {
                return this.arg4Field;
            }
            set {
                this.arg4Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ctrl.client.mbap.shine.com/")]
    public partial class queryZdQueryRepResponse {
        
        private guDongListDTO returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public guDongListDTO @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ctrl.client.mbap.shine.com/")]
    public partial class addZdQueryReq {
        
        private string arg0Field;
        
        private string arg1Field;
        
        private string arg2Field;
        
        private string arg3Field;
        
        private string arg4Field;
        
        private string arg5Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string arg1 {
            get {
                return this.arg1Field;
            }
            set {
                this.arg1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string arg2 {
            get {
                return this.arg2Field;
            }
            set {
                this.arg2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string arg3 {
            get {
                return this.arg3Field;
            }
            set {
                this.arg3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string arg4 {
            get {
                return this.arg4Field;
            }
            set {
                this.arg4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string arg5 {
            get {
                return this.arg5Field;
            }
            set {
                this.arg5Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ctrl.client.mbap.shine.com/")]
    public partial class addZdQueryReqResponse {
        
        private olReturnMsgDTO returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public olReturnMsgDTO @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ctrl.client.mbap.shine.com/")]
    public partial class addShzdjycxWt {
        
        private string arg0Field;
        
        private string arg1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string arg1 {
            get {
                return this.arg1Field;
            }
            set {
                this.arg1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ctrl.client.mbap.shine.com/")]
    public partial class addShzdjycxWtResponse {
        
        private olReturnMsgDTO returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public olReturnMsgDTO @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ctrl.client.mbap.shine.com/")]
    public partial class queryShzdjycxHb {
        
        private string arg0Field;
        
        private string arg1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string arg1 {
            get {
                return this.arg1Field;
            }
            set {
                this.arg1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ctrl.client.mbap.shine.com/")]
    public partial class queryShzdjycxHbResponse {
        
        private shzdjyListDTO returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public shzdjyListDTO @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getLocalCertCheckCompletedEventHandler(object sender, getLocalCertCheckCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getLocalCertCheckCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getLocalCertCheckCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getLocalCertCheckResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getLocalCertCheckResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void submitIdenCheckCompletedEventHandler(object sender, submitIdenCheckCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class submitIdenCheckCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal submitIdenCheckCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public submitIdenCheckResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((submitIdenCheckResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void reqSMSCodeByPhoneCompletedEventHandler(object sender, reqSMSCodeByPhoneCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class reqSMSCodeByPhoneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal reqSMSCodeByPhoneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public reqSMSCodeByPhoneResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((reqSMSCodeByPhoneResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void checkPhoneCompletedEventHandler(object sender, checkPhoneCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkPhoneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checkPhoneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public checkPhoneResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((checkPhoneResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void checkFullAccountCompletedEventHandler(object sender, checkFullAccountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkFullAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checkFullAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public checkFullAccountResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((checkFullAccountResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void queryZdQueryRepCompletedEventHandler(object sender, queryZdQueryRepCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryZdQueryRepCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryZdQueryRepCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public queryZdQueryRepResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((queryZdQueryRepResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void addZdQueryReqCompletedEventHandler(object sender, addZdQueryReqCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addZdQueryReqCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addZdQueryReqCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public addZdQueryReqResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((addZdQueryReqResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void addShzdjycxWtCompletedEventHandler(object sender, addShzdjycxWtCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addShzdjycxWtCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addShzdjycxWtCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public addShzdjycxWtResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((addShzdjycxWtResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void queryShzdjycxHbCompletedEventHandler(object sender, queryShzdjycxHbCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryShzdjycxHbCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryShzdjycxHbCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public queryShzdjycxHbResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((queryShzdjycxHbResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591